### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by htc16**

### CODE REVIEW

**Comment by ZhengPeiRu21** [comment]
Thank you for take time to submit this PR. I am sorry, but I do not believe this change is correct. string.h is a C header and should never be needed in a C++ project. string is the correct C++ library that contains std::string which is used in this file. Please see: https://stackoverflow.com/questions/9257665/difference-between-string-and-string-h

Are you seeing compile error with the string header? If you are, we should change whatever is using it because string.h is deprecated in C++.

It does look as string.h is used in some classes of AzerothCore but this is not best practice, so it is best if we can avoid it.

**Comment by htc16** [comment]
I'm a layman, but I was able to compile on Linux when I added that `.h`

**Comment by ZhengPeiRu21** [comment]
> I'm a layman, but I was able to compile on Linux when I added that `.h`

Okay, thank you for confirm. It is strange that this would prevent successful compile, but if this change fixes the problem, then we can accept it.

**Comment by Winfidonarleyan** [comment]
What is this pr? This rofl?

**Pull request merged**
