### PR TITLE
Update LfgActions.cpp

### PR DESCRIPTION
**Pull request by Embracefate989**
Fixing naming issues for "minlevel", "maxlevel" and "name" not being capitalized properly also changing "type" to "TypeID" causing failures while compiling.

### CODE REVIEW

**Comment by rookis1** [comment]
nice!

**Comment by wushiwein119** [comment]
赞，确实有这个问题，我也是自己修改了，才能正常编译

**Comment by worm0908** [comment]
👍👍

**Comment by ZhengPeiRu21** [comment]
Thank you for the PR. Sorry for the delay with getting this reviewed and merged - I was out on vacation and I am just now catching up.

**Pull request merged**
